### ISSUE TITLE
Use MvxRecyclerView instead of MvxListView

### ISSUE THREAD

**Issue by martijn00** [simonjaeger/xamarin-csharp-propertymanager-sample#2]
For better performance and optimizations `MvxRecyclerView` should be used to show lists.

**Comment by jasonjoh** [comment]
Thanks for your interest in Microsoft Graph! We are archiving this sample, so I'm closing this issue. For a replacement Xamarin app sample, please see https://github.com/microsoftgraph/msgraph-training-xamarin. We apologize for any inconvenience.
