### ISSUE TITLE
Stop in login 

### ISSUE THREAD

**Issue by free86011** [simonjaeger/xamarin-csharp-propertymanager-sample#7]
I follow the step to build the project. When I launch the project and login in with Microsoft account, it stop in the login view as attachment.
![stopview](https://user-images.githubusercontent.com/48471229/54183988-781c6280-44e0-11e9-8d33-923f6f6d5aa3.png)

**Comment by jasonjoh** [comment]
Thanks for your interest in Microsoft Graph! We are archiving this sample, so I'm closing this issue. For a replacement Xamarin app sample, please see https://github.com/microsoftgraph/msgraph-training-xamarin. We apologize for any inconvenience.
